const FETCHING_CITIES = "FETCHING_CITIES";
const FETCHED_CITIES = "FETCHING_CITIES";
const SELECT_CITY = "SELECT_CITY";
const FETCHING_HOTELS = "FETCHING_HOTELS";
const FETCHED_HOTELS = "FETCHED_HOTELS";
const HOTEL_DETAILS = "HOTEL_DETAILS";

export {
  FETCHING_CITIES,
  FETCHED_CITIES,
  SELECT_CITY,
  FETCHING_HOTELS,
  FETCHED_HOTELS,
  HOTEL_DETAILS,
};